# Pre-commit configuration for the Company OS
#
# To install the pre-commit hooks:
#   pip install pre-commit
#   pre-commit install
#
# To run manually:
#   pre-commit run --all-files

repos:
# Company OS Validation Services (Local Bazel targets)
-   repo: local
    hooks:
    # Source Truth Enforcement - Run first to catch consistency issues
    -   id: source-truth-check
        name: Source Truth Enforcement
        description: Validate repository-wide consistency and source of truth alignment
        entry: bazel run //company_os/domains/source_truth_enforcement/adapters/cli:source_truth_cli -- check --all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: false

    # Rules Service - Document validation and sync
    -   id: rules-sync
        name: Rules Service - Sync
        description: Synchronize rules to agent folders
        entry: bazel run //company_os/domains/rules_service/adapters/cli:rules_cli -- rules sync
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: false

    -   id: rules-validate
        name: Rules Service - Validate
        description: Validate markdown files against rules (auto-fix enabled)
        entry: bazel run //company_os/domains/rules_service/adapters/cli:rules_cli -- validate validate --auto-fix
        language: system
        types: [markdown]
        stages: [pre-commit]
        verbose: false

    # Test Suites - Run all available tests
    -   id: rules-service-tests
        name: Rules Service Tests
        description: Run all Rules Service test suites
        entry: bazel test //company_os/domains/rules_service/tests:all_tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: false

# Python code quality tools (using ruff and mypy directly)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
    -   id: ruff
        name: Lint with Ruff
        args: [--fix]
    -   id: ruff-format
        name: Format with Ruff

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
    -   id: mypy
        name: Type check with MyPy
        additional_dependencies: [types-PyYAML, types-requests]
        args: [--ignore-missing-imports]

# Standard pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^bazel-|\.lock$'
    -   id: end-of-file-fixer
        exclude: '^bazel-|\.lock$'
    -   id: check-yaml
        exclude: '^bazel-'
    -   id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: '^bazel-|\.lock$'
    -   id: check-merge-conflict
